CREATE TABLE APPLICATION
(
    ID              VARCHAR2(40) NOT NULL PRIMARY KEY,
    STATUS          VARCHAR2(40) NOT NULL,
    ROUTE_ID        VARCHAR2(40) NOT NULL,
    DRIVER_ID       VARCHAR2(40),
    VEHICLE_TYPE_ID INTEGER,
    CREATED_DATE    TIMESTAMP NOT NULL
);
ALTER TABLE APPLICATION ADD FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE(ID);
