CREATE TABLE APPLICATION
(
    ID VARCHAR2(40) NOT NULL PRIMARY KEY,
    STATUS VARCHAR2(40) NOT NULL,
    ROUTE_ID VARCHAR2(40) NOT NULL FOREIGN KEY REFERENCES ROUTE(ID),
    DRIVER_ID VARCHAR2(40),
    VEHICLE_TYPE_ID INTEGER,
    CREATED_DATE TIMESTAMP NOT NULL
);
