logging:
  level:
    web: debug

spring:
  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  docker:
    compose:
      enabled: false
axon:
  serializer:
    general: jackson
  axonserver:
    enabled: false
